name: Build

on:
  push:
    branches:
      - marshmallow-mr1-release
    paths:
      - '.github/workflows/build.yml'
      - 'app/**'
      - 'gradle/wrapper/gradle-wrapper.properties'
      - '*.gradle'
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        type: boolean
        required: true
        default: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Build
        run: | 
          ./gradlew assembleRelease -q
          echo "version=$(grep versionName app/build.gradle | awk '{print $2}' | tr -d \")" >> $GITHUB_ENV
          echo "commit=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Music (${{ env.version }}@${{ env.commit }})
          path: app/build/outputs/apk/release/app-release.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event.inputs.release == 'true'
        with:
          tag_name: ${{ env.version }}
          draft: true
          prerelease: false
          files: app/build/outputs/apk/release/app-release.apk
